// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SAN_TileToner","status":true,"description":"タイルトナー 1.1.6\r\nマップのタイルを染色します。","parameters":{"ShowBaseTone":"ON","FadingDuration":"15"}}
];
